# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDvbiSBJHMNIGqZQoijxZQp6KC4qtpeG

**Task 7 ML***
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import re

def parse_log_file(file_path):
    """Raw log file ko parse karke DataFrame banata hai"""
    data = []
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            ip_match = re.search(r'(\d{1,3}(?:\.\d{1,3}){3})', line)
            ip = ip_match.group(1) if ip_match else '127.0.0.1'

            status_match = re.search(r'\s([1-5]\d{2})\s', line)
            status = int(status_match.group(1)) if status_match else 200

            size_match = re.search(r'\s(\d+)\s*$', line.strip())
            size = int(size_match.group(1)) if size_match else 0

            method_match = re.search(r'"(GET|POST|PUT|DELETE|HEAD)', line)
            method = method_match.group(1) if method_match else 'GET'

            data.append({
                'ip': ip,
                'method': method,
                'status': status,
                'payload_size': size,
                'raw_log': line.strip()
            })
    return pd.DataFrame(data)

def extract_features(df):
    features = df.groupby('ip').agg(
        total_requests=('ip', 'count'),
        error_404_count=('status', lambda x: (x == 404).sum()),
        server_error_count=('status', lambda x: (x >= 500).sum()),
        avg_payload_size=('payload_size', 'mean'),
        max_payload_size=('payload_size', 'max')
    ).reset_index()
    return features

def detect_anomalies(features_df):
    X = features_df[['total_requests', 'error_404_count', 'server_error_count', 'avg_payload_size', 'max_payload_size']]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = IsolationForest(contamination=0.05, random_state=42)
    features_df['anomaly'] = model.fit_predict(X_scaled)
    return features_df

if __name__ == "__main__":
    log_file = "logfiles.log"
    print("[INFO] Parsing raw server logs...")
    raw_df = parse_log_file(log_file)
    print(f"[INFO] Successfully parsed {len(raw_df)} log lines.")

    print("[INFO] Extracting technical features per IP...")
    features = extract_features(raw_df)

    print("[INFO] Running Unsupervised Anomaly Detection (Isolation Forest)...")
    analyzed_df = detect_anomalies(features)

    threats = analyzed_df[analyzed_df['anomaly'] == -1]
    print(f"\n[ALERT] Detected {len(threats)} anomalous IPs!")
    print(threats.head())